#############################################################################
# Makefile for building: bin/PointPlotter
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Nov 7 12:18:45 2016
# Project:  PointPlotter.pro
# Template: app
# Command: /usr/local/software/qt4/bin/qmake -o Makefile PointPlotter.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/software/qt-4.8.6/mkspecs/linux-g++-64 -I. -I/usr/local/software/qt-4.8.6/include/QtCore -I/usr/local/software/qt-4.8.6/include/QtGui -I/usr/local/software/qt-4.8.6/include -Iinclude -Itmp
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/local/software/qt-4.8.6/lib
LIBS          = $(SUBLIBS)  -L/usr/local/software/qt-4.8.6/lib -lQtGui -Wl,-rpath,/usr/local/software/qt4/lib -L/usr/local/software/qt4/lib -L/usr/X11R6/lib64 -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -lQtCore -Wl,-rpath,/usr/local/software/qt4/lib -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/software/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/PointPlotter.cpp \
		src/point_plotter_window.cpp \
		src/point_plotter_frame.cpp \
		src/findline.cpp \
		src/fast.cpp \
		src/brute.cpp \
		src/point.cpp tmp/moc_point_plotter_window.cpp \
		tmp/moc_point_plotter_frame.cpp
OBJECTS       = obj/PointPlotter.o \
		obj/point_plotter_window.o \
		obj/point_plotter_frame.o \
		obj/findline.o \
		obj/fast.o \
		obj/brute.o \
		obj/point.o \
		obj/moc_point_plotter_window.o \
		obj/moc_point_plotter_frame.o
DIST          = /usr/local/software/qt-4.8.6/mkspecs/common/unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri \
		/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/release.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		PointPlotter.pro
QMAKE_TARGET  = PointPlotter
DESTDIR       = bin/
TARGET        = bin/PointPlotter

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET) test/Gen bin/Fast bin/Brute

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	cp -r resource/* bin

Makefile: PointPlotter.pro  /usr/local/software/qt-4.8.6/mkspecs/linux-g++-64/qmake.conf /usr/local/software/qt-4.8.6/mkspecs/common/unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri \
		/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/release.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		/usr/local/software/qt-4.8.6/lib/libQtGui.prl \
		/usr/local/software/qt-4.8.6/lib/libQtCore.prl
	$(QMAKE) -o Makefile PointPlotter.pro
/usr/local/software/qt-4.8.6/mkspecs/common/unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri:
/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri:
/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/release.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf:
/usr/local/software/qt-4.8.6/lib/libQtGui.prl:
/usr/local/software/qt-4.8.6/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile PointPlotter.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/PointPlotter1.0.0 || $(MKDIR) obj/PointPlotter1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/PointPlotter1.0.0/ && $(COPY_FILE) --parents include/point_plotter_window.h include/point_plotter_frame.h include/findline.h include/fast.h include/brute.h include/point.h obj/PointPlotter1.0.0/ && $(COPY_FILE) --parents src/PointPlotter.cpp src/point_plotter_window.cpp src/point_plotter_frame.cpp src/findline.cpp src/fast.cpp src/brute.cpp src/point.cpp obj/PointPlotter1.0.0/ && (cd `dirname obj/PointPlotter1.0.0` && $(TAR) PointPlotter1.0.0.tar PointPlotter1.0.0 && $(COMPRESS) PointPlotter1.0.0.tar) && $(MOVE) `dirname obj/PointPlotter1.0.0`/PointPlotter1.0.0.tar.gz . && $(DEL_FILE) -r obj/PointPlotter1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: tmp/moc_point_plotter_window.cpp tmp/moc_point_plotter_frame.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) tmp/moc_point_plotter_window.cpp tmp/moc_point_plotter_frame.cpp
tmp/moc_point_plotter_window.cpp: include/point_plotter_frame.h \
		include/findline.h \
		include/point.h \
		include/fast.h \
		include/brute.h \
		include/point_plotter_window.h
	/usr/local/software/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) include/point_plotter_window.h -o tmp/moc_point_plotter_window.cpp

tmp/moc_point_plotter_frame.cpp: include/findline.h \
		include/point.h \
		include/fast.h \
		include/brute.h \
		include/point_plotter_frame.h
	/usr/local/software/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) include/point_plotter_frame.h -o tmp/moc_point_plotter_frame.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/PointPlotter.o: src/PointPlotter.cpp include/point_plotter_window.h \
		include/point_plotter_frame.h \
		include/findline.h \
		include/point.h \
		include/fast.h \
		include/brute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/PointPlotter.o src/PointPlotter.cpp

obj/point_plotter_window.o: src/point_plotter_window.cpp include/point_plotter_window.h \
		include/point_plotter_frame.h \
		include/findline.h \
		include/point.h \
		include/fast.h \
		include/brute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/point_plotter_window.o src/point_plotter_window.cpp

obj/point_plotter_frame.o: src/point_plotter_frame.cpp include/point_plotter_frame.h \
		include/findline.h \
		include/point.h \
		include/fast.h \
		include/brute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/point_plotter_frame.o src/point_plotter_frame.cpp

obj/findline.o: src/findline.cpp include/findline.h \
		include/point.h \
		include/fast.h \
		include/brute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/findline.o src/findline.cpp

obj/fast.o: src/fast.cpp include/fast.h \
		include/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/fast.o src/fast.cpp

obj/brute.o: src/brute.cpp include/brute.h \
		include/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/brute.o src/brute.cpp

obj/point.o: src/point.cpp include/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/point.o src/point.cpp

obj/moc_point_plotter_window.o: tmp/moc_point_plotter_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_point_plotter_window.o tmp/moc_point_plotter_window.cpp

obj/moc_point_plotter_frame.o: tmp/moc_point_plotter_frame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_point_plotter_frame.o tmp/moc_point_plotter_frame.cpp

test/Gen: test/gen_exe.cpp include/point.h
	$(CXX) $(CXXFLAGS) $(INCPATH) -o test/Gen src/point.cpp test/gen_exe.cpp

bin/Fast: src/fast_exe.cpp \
		include/findline.h \
		include/point.h \
		include/fast.h \
		include/brute.h
	$(CXX) $(CXXFLAGS) $(INCPATH) -o bin/Fast src/point.cpp src/fast.cpp src/brute.cpp src/findline.cpp src/fast_exe.cpp

bin/Brute: src/brute_exe.cpp \
		include/findline.h \
		include/point.h \
		include/fast.h \
		include/brute.h
	$(CXX) $(CXXFLAGS) $(INCPATH) -o bin/Brute src/point.cpp src/fast.cpp src/brute.cpp src/findline.cpp src/brute_exe.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

